logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.cp: DEBUG
    me.chanjar.weixin: DEBUG
wechat:
  cp:
    corpId: ww99c821ef5abf9550
    appConfigs:
      - agentId: 1000003
        secret: s43khxFXtTMnpONe9tgwpnoxPSGb5F-ZcN0sTPAk_mY
        token: 111
        aesKey: 111

server:
  port: 8000

spring:
    application:
      name: demo
    # REDIS (RedisProperties)
    redis:
        # Redis数据库索引（默认为0）
        #database: 0
        # Redis服务器地址
        host: svc-redis.c.svc.mhc.local
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: 123456
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 20
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: 10000
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0
            # 连接超时时间（毫秒）
        timeout: 5000
